export const FONT_OPTIONS = [
  { value: "\"Atkinson Hyperlegible\", \"Verdana\", sans-serif", label: "Atkinson Hyperlegible" },
  { value: "\"Luciole\", \"Verdana\", sans-serif", label: "Luciole" },
  { value: "\"Lexie Readable\", \"Verdana\", sans-serif", label: "Lexie Readable" },
  { value: "\"OpenDyslexic\", \"Arial\", sans-serif", label: "OpenDyslexic" },
  { value: "\"Aptos\", \"Segoe UI\", sans-serif", label: "Aptos" },
  { value: "\"Arial\", \"Helvetica Neue\", sans-serif", label: "Arial" },
  { value: "\"Verdana\", \"Geneva\", sans-serif", label: "Verdana" },
  { value: "\"Tahoma\", sans-serif", label: "Tahoma" },
  { value: "\"Trebuchet MS\", sans-serif", label: "Trebuchet MS" },
  { value: "\"Segoe UI\", sans-serif", label: "Segoe UI" },
  { value: "\"Century Gothic\", sans-serif", label: "Century Gothic" },
  { value: "\"Comic Sans MS\", cursive, sans-serif", label: "Comic Sans MS" }
];

export const THEME_TOKENS = {
  creme: {
    page: "#f4efe1",
    panel: "#fbf7ec",
    panelStrong: "#efe7d1",
    canvas: "#f8f3e7",
    text: "#26374a",
    textSoft: "#667587",
    accent: "#456b97",
    accentStrong: "#2f4f76",
    accentSoft: "#e3eaf3",
    border: "#ddd3bd",
    shadow: "rgba(82, 93, 111, 0.12)",
    block: "rgba(251, 247, 236, 0.88)",
    highlight: "rgba(194, 215, 238, 0.3)",
    ruler: "rgba(69, 107, 151, 0.1)",
    syllabe1: "#426389",
    syllabe2: "#4d7e76",
    muet: "#a9afb8",
    important: "rgba(194, 215, 238, 0.58)"
  },
  brume: {
    page: "#edf3f8",
    panel: "#f7fbff",
    panelStrong: "#d9e5f1",
    canvas: "#f1f7fc",
    text: "#24384d",
    textSoft: "#627486",
    accent: "#4f78ab",
    accentStrong: "#33577f",
    accentSoft: "#dbe8f5",
    border: "#c9d7e6",
    shadow: "rgba(86, 95, 110, 0.11)",
    block: "rgba(247, 251, 255, 0.9)",
    highlight: "rgba(191, 219, 254, 0.28)",
    ruler: "rgba(79, 120, 171, 0.1)",
    syllabe1: "#4f78ab",
    syllabe2: "#5d857c",
    muet: "#aeb3ba",
    important: "rgba(191, 219, 254, 0.56)"
  },
  contraste: {
    page: "#eaf2fb",
    panel: "#f7fbff",
    panelStrong: "#d8e6f6",
    canvas: "#f3f8fe",
    text: "#16324d",
    textSoft: "#566b80",
    accent: "#2f67b2",
    accentStrong: "#1d4f8b",
    accentSoft: "#d8e8fb",
    border: "#bfd2e8",
    shadow: "rgba(70, 80, 96, 0.14)",
    block: "rgba(247, 251, 255, 0.94)",
    highlight: "rgba(177, 208, 243, 0.34)",
    ruler: "rgba(47, 103, 178, 0.12)",
    syllabe1: "#2f67b2",
    syllabe2: "#3f7e9a",
    muet: "#98a3ae",
    important: "rgba(177, 208, 243, 0.62)"
  },
  blanc: {
    page: "#f4f7fb",
    panel: "#fdfefe",
    panelStrong: "#eef3f8",
    canvas: "#fafbfc",
    text: "#24364a",
    textSoft: "#66778b",
    accent: "#4c78ac",
    accentStrong: "#325b89",
    accentSoft: "#dde8f5",
    border: "#d6dee8",
    shadow: "rgba(80, 92, 108, 0.1)",
    block: "rgba(250, 251, 252, 0.96)",
    highlight: "rgba(191, 219, 254, 0.24)",
    ruler: "rgba(76, 120, 172, 0.1)",
    syllabe1: "#3f6fa7",
    syllabe2: "#4c8078",
    muet: "#a7afba",
    important: "rgba(191, 219, 254, 0.52)"
  },
  neutre: {
    page: "#f1f3f5",
    panel: "#fafbfc",
    panelStrong: "#e9edf2",
    canvas: "#fdfefe",
    text: "#2b3744",
    textSoft: "#6a7582",
    accent: "#5b7391",
    accentStrong: "#425a75",
    accentSoft: "#dde5ef",
    border: "#d4dbe4",
    shadow: "rgba(82, 90, 100, 0.1)",
    block: "rgba(250, 251, 252, 0.94)",
    highlight: "rgba(205, 218, 232, 0.28)",
    ruler: "rgba(91, 115, 145, 0.1)",
    syllabe1: "#4a698d",
    syllabe2: "#587a74",
    muet: "#a5adb6",
    important: "rgba(205, 218, 232, 0.54)"
  },
  nuitDouce: {
    page: "#e8edf1",
    panel: "#f3f7fa",
    panelStrong: "#d6dfe7",
    canvas: "#edf3f7",
    text: "#263544",
    textSoft: "#647282",
    accent: "#5c7898",
    accentStrong: "#3f5975",
    accentSoft: "#dde7f0",
    border: "#c7d2dc",
    shadow: "rgba(74, 87, 102, 0.12)",
    block: "rgba(243, 247, 250, 0.9)",
    highlight: "rgba(188, 209, 233, 0.3)",
    ruler: "rgba(92, 120, 152, 0.1)",
    syllabe1: "#5c7898",
    syllabe2: "#5c8079",
    muet: "#a3adb7",
    important: "rgba(188, 209, 233, 0.56)"
  }
};

export const APP_THEME_TOKENS = {
  clair: {
    colorScheme: "light",
    uiPage: "#ece6de",
    uiShell: "#f7f2eb",
    uiPanel: "#fdfbf7",
    uiPanelStrong: "#f3ece2",
    uiText: "#1a1613",
    uiTextSoft: "#6d655d",
    uiAccent: "#b08a58",
    uiAccentStrong: "#8f6c43",
    uiAccentSoft: "#eadcc8",
    uiBorder: "#d8cec2",
    uiWarningBg: "#f3ede4",
    uiWarningText: "#6f5533",
    uiShellShadow: "0 18px 40px rgba(22, 16, 12, 0.09)",
    shadowSoft: "0 10px 26px rgba(22, 16, 12, 0.05)",
    shadowPress: "0 14px 28px rgba(155, 118, 72, 0.16)"
  },
  intermediaire: {
    colorScheme: "light",
    uiPage: "#e6e0d8",
    uiShell: "#f1ebe4",
    uiPanel: "#f8f4ee",
    uiPanelStrong: "#ece3d8",
    uiText: "#1c1815",
    uiTextSoft: "#675f58",
    uiAccent: "#a78254",
    uiAccentStrong: "#856641",
    uiAccentSoft: "#e3d3bc",
    uiBorder: "#cec2b3",
    uiWarningBg: "#efe5d8",
    uiWarningText: "#694f31",
    uiShellShadow: "0 18px 42px rgba(24, 18, 14, 0.11)",
    shadowSoft: "0 10px 24px rgba(24, 18, 14, 0.06)",
    shadowPress: "0 14px 28px rgba(133, 102, 65, 0.18)"
  },
  sombre: {
    colorScheme: "dark",
    uiPage: "#12100f",
    uiShell: "#191614",
    uiPanel: "#201c19",
    uiPanelStrong: "#2a2521",
    uiText: "#f2ece5",
    uiTextSoft: "#c7bdb1",
    uiAccent: "#c49b64",
    uiAccentStrong: "#e0bf8e",
    uiAccentSoft: "#3e3428",
    uiBorder: "#3a322b",
    uiWarningBg: "#2a241f",
    uiWarningText: "#e6c998",
    uiShellShadow: "0 18px 44px rgba(0, 0, 0, 0.42)",
    shadowSoft: "0 12px 28px rgba(0, 0, 0, 0.28)",
    shadowPress: "0 16px 30px rgba(0, 0, 0, 0.34)"
  }
};

export const DEFAULT_PREFERENCES = {
  fontFamily: "\"Verdana\", \"Geneva\", sans-serif",
  fontSize: 21,
  lineHeight: 1.8,
  letterSpacing: 0.12,
  wordSpacing: 0.16,
  maxLineLength: 68,
  pagePadding: 30,
  appTheme: "intermediaire",
  theme: "brume",
  overlayPreset: "none",
  overlayOpacity: 0.1,
  overlayCustomColor: "#dbeafe",
  highlightMode: "soft",
  focusMode: "none",
  colorationMode: "none",
  syllableLevel: "off",
  soundColorMode: "soft",
  syllableBreakMode: "none",
  readingGuideMode: "off",
  readingGuideLines: 1,
  readingGuideOpacity: 0.16,
  readingGuideColor: "#a0344a",
  verificationMode: "off",
  speechRate: 1,
  pauseBetweenSentences: 0,
  speechVoiceId: "",
  ocrLanguage: "fra",
  distractionFree: false
};

export const BUILTIN_PROFILES = [
  {
    id: "normal",
    label: "Normal",
    description: "Affiche le texte reconstruit sans aide au décodage ni repères supplémentaires.",
    editable: true,
    researchNotes: "Mode sobre pour lire le texte importé en reflow, sans coloration, syllabes, focus ou réglette.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"Aptos\", \"Segoe UI\", sans-serif",
      fontSize: 20,
      lineHeight: 1.8,
      letterSpacing: 0.12,
      wordSpacing: 0.16,
      maxLineLength: 72,
      theme: "neutre",
      overlayPreset: "none",
      overlayOpacity: 0,
      focusMode: "none",
      highlightMode: "none",
      colorationMode: "none",
      syllableLevel: "off",
      soundColorMode: "soft",
      syllableBreakMode: "none",
      readingGuideMode: "off",
      verificationMode: "off"
    }
  },
  {
    id: "lecture-visuelle-allegee",
    label: "Lecture visuelle allégée",
    description: "Une lecture stable, aérée et confortable pour les textes longs.",
    editable: true,
    researchNotes: "Profil de base recommandé pour une lecture calme, avec colonne modérée et contraste doux.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"Verdana\", \"Geneva\", sans-serif",
      fontSize: 22,
      lineHeight: 1.8,
      letterSpacing: 0.12,
      wordSpacing: 0.18,
      maxLineLength: 66,
      pagePadding: 34,
      theme: "brume",
      overlayPreset: "none",
      overlayOpacity: 0,
      focusMode: "none",
      highlightMode: "soft",
      colorationMode: "none",
      syllableLevel: "off",
      soundColorMode: "soft",
      syllableBreakMode: "none",
      readingGuideMode: "off",
      verificationMode: "off"
    }
  },
  {
    id: "audio",
    label: "Audio / Focus",
    description: "Optimise l’affichage pour suivre le texte avec la lecture vocale et le repérage visuel.",
    editable: true,
    researchNotes: "Accent sur la stabilité visuelle pendant la synthèse vocale, avec un focus utile sans surcharge.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"Verdana\", \"Geneva\", sans-serif",
      fontSize: 22,
      lineHeight: 1.9,
      letterSpacing: 0.12,
      wordSpacing: 0.2,
      maxLineLength: 62,
      theme: "brume",
      focusMode: "paragraph",
      highlightMode: "none",
      colorationMode: "none",
      syllableLevel: "off",
      soundColorMode: "soft",
      syllableBreakMode: "none",
      readingGuideMode: "off",
      pauseBetweenSentences: 500
    }
  },
  {
    id: "decodage-renforce",
    label: "Décodage renforcé",
    description: "Active une aide visuelle plus marquée pour syllabes et repères de lecture.",
    editable: true,
    researchNotes: "Renforce les appuis visuels sans surcharge, avec focus léger et coloration douce.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"OpenDyslexic\", \"Arial\", sans-serif",
      fontSize: 22,
      lineHeight: 1.85,
      letterSpacing: 0.12,
      wordSpacing: 0.2,
      maxLineLength: 58,
      theme: "contraste",
      focusMode: "none",
      highlightMode: "soft",
      colorationMode: "pedagogique",
      syllableLevel: "strong",
      soundColorMode: "soft",
      syllableBreakMode: "dot",
      readingGuideMode: "ruler",
      readingGuideLines: 1,
      readingGuideOpacity: 0.14
    }
  },
  {
    id: "comprehension-simplifiee",
    label: "Compréhension simplifiée",
    description: "Augmente le confort de lecture pour alléger l’effort cognitif.",
    editable: true,
    researchNotes: "Colonne plus étroite, interligne généreux et repérage renforcé pour mieux suivre le sens.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"Arial\", \"Helvetica Neue\", sans-serif",
      fontSize: 24,
      lineHeight: 1.95,
      letterSpacing: 0.12,
      wordSpacing: 0.22,
      maxLineLength: 56,
      pagePadding: 34,
      theme: "nuitDouce",
      focusMode: "paragraph",
      highlightMode: "strong",
      colorationMode: "none",
      syllableLevel: "off",
      soundColorMode: "soft",
      syllableBreakMode: "none",
      readingGuideMode: "window",
      readingGuideLines: 2
    }
  },
  {
    id: "dyslexie-legere",
    label: "Dyslexie",
    description: "Réglages équilibrés pour une lecture plus fluide avec aide au décodage modérée.",
    editable: true,
    researchNotes: "Profil principal dyslexie : espacements utiles, fond doux et aide légère sans surcharge.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"Verdana\", \"Geneva\", sans-serif",
      fontSize: 22,
      lineHeight: 1.95,
      letterSpacing: 0.12,
      wordSpacing: 0.2,
      maxLineLength: 60,
      theme: "creme",
      overlayPreset: "creme",
      overlayOpacity: 0.06,
      highlightMode: "none",
      colorationMode: "pedagogique",
      syllableLevel: "light",
      soundColorMode: "soft",
      syllableBreakMode: "none",
      readingGuideMode: "off"
    }
  },
  {
    id: "dyslexie-severe",
    label: "Dyslexie renforcée",
    description: "Réglages renforcés avec aide au décodage plus marquée et réglette active.",
    editable: true,
    researchNotes: "Profil fort pour lecture lente, avec grands espacements, OpenDyslexic, audio et réglette.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"OpenDyslexic\", \"Arial\", sans-serif",
      fontSize: 24,
      lineHeight: 2.2,
      letterSpacing: 0.15,
      wordSpacing: 0.25,
      maxLineLength: 54,
      theme: "creme",
      overlayPreset: "creme",
      overlayOpacity: 0.1,
      colorationMode: "sonsFrancais",
      syllableLevel: "strong",
      soundColorMode: "strong",
      syllableBreakMode: "dot",
      readingGuideMode: "ruler",
      readingGuideLines: 1,
      speechRate: 0.9,
      pauseBetweenSentences: 700
    }
  },
  {
    id: "dyscalculie",
    label: "Dyscalculie",
    description: "Optimise la lecture des nombres et expressions mathématiques.",
    editable: true,
    researchNotes: "Accent sur lisibilite des nombres, verbalisation et repere calme pour les formules.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"Atkinson Hyperlegible\", \"Verdana\", sans-serif",
      fontSize: 20,
      lineHeight: 2,
      letterSpacing: 0.12,
      wordSpacing: 0.16,
      maxLineLength: 60,
      theme: "creme",
      colorationMode: "none",
      syllableLevel: "off",
      readingGuideMode: "off",
      verificationMode: "markers",
      speechRate: 0.95
    }
  },
  {
    id: "tdah",
    label: "TDAH - Attention",
    description: "Mode concentré avec fenêtre de lecture et interface allégée.",
    editable: true,
    researchNotes: "Profil centre sur l'attention soutenue : largeur plus etroite, immersion et fenetre de lecture.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"Verdana\", \"Geneva\", sans-serif",
      fontSize: 20,
      lineHeight: 2,
      letterSpacing: 0.12,
      wordSpacing: 0.16,
      maxLineLength: 54,
      theme: "creme",
      overlayPreset: "grey",
      overlayOpacity: 0.1,
      colorationMode: "none",
      syllableLevel: "off",
      readingGuideMode: "window",
      readingGuideLines: 3,
      distractionFree: true,
      speechRate: 0.95,
      pauseBetweenSentences: 600
    }
  },
  {
    id: "dyspraxie",
    label: "Dyspraxie - Motricité",
    description: "Grandes cibles, lecture stable et navigation clavier confortable.",
    editable: true,
    researchNotes: "Profil confortable pour usage clavier, avec grands espacements et reglette simple.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"Verdana\", \"Geneva\", sans-serif",
      fontSize: 22,
      lineHeight: 2,
      letterSpacing: 0.12,
      wordSpacing: 0.2,
      maxLineLength: 64,
      theme: "creme",
      overlayPreset: "blue",
      overlayOpacity: 0.08,
      colorationMode: "none",
      syllableLevel: "off",
      readingGuideMode: "ruler",
      readingGuideLines: 1
    }
  },
  {
    id: "enseignant",
    label: "Enseignant / Ortho",
    description: "Vue de travail pour preparer une lecture adaptee et verifier le rendu.",
    editable: true,
    researchNotes: "Profil d'analyse avec contraste doux, verification visible et decodage modere.",
    defaults: {
      ...DEFAULT_PREFERENCES,
      fontFamily: "\"Atkinson Hyperlegible\", \"Verdana\", sans-serif",
      fontSize: 18,
      lineHeight: 1.8,
      letterSpacing: 0.12,
      wordSpacing: 0.16,
      maxLineLength: 70,
      theme: "creme",
      colorationMode: "pedagogique",
      syllableLevel: "light",
      soundColorMode: "soft",
      verificationMode: "markers",
      readingGuideMode: "off"
    }
  }
];
